spring:
  application:
    name: auth-service
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 1000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: follow-updates-group
      auto-offset-reset: earliest

server:
  port: 8080
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
