server:
  port: 8081

spring:
  application:
    name: friend-service
  data:
    redis:
      host: localhost
      port: 6379
      # password: your-redis-password # Bỏ nếu không dùng mật khẩu
      timeout: 2000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 1000
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

firebase:
  service-account-path: firebase/serviceAccountKey.json
#logging:
#  level:
#    org.springframework: DEBUG
#    com.netflix.discovery: DEBUG